title: 'Blueflood'
github: 'https://github.com/rackerlabs/blueflood'
baseurl: ""
google_analytics: "UA-42769648-1"
highlighter: pygments
markdown:    kramdown
kramdown:
  input: GFM
  toc_levels: "1..3"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
collections:
  docs:
    output: true
    permalink: /docs/:path/
sass:
    sass_dir: _scss
    style: :compressed
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"